# Generated by Django 2.0.3 on 2018-04-25 10:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaints',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.TextField()),
                ('date_time', models.DateTimeField()),
                ('complaint_text', models.TextField()),
                ('complainant', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('0', 'Pending'), ('1', 'Resolved')], max_length=10)),
                ('complaint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('dob', models.DateField()),
                ('address', models.CharField(max_length=200)),
                ('marital_status', models.CharField(max_length=30)),
                ('contact', models.IntegerField()),
                ('joining_date', models.DateField()),
                ('position', models.CharField(max_length=100)),
                ('emp_status', models.CharField(max_length=70)),
                ('salary', models.FloatField()),
                ('bank_name', models.CharField(max_length=100)),
                ('bank_account', models.IntegerField()),
                ('skill_set', models.TextField()),
                ('image', models.ImageField(upload_to='HR/static/HR')),
                ('emp', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback_text', models.TextField()),
                ('respondent', models.CharField(max_length=50)),
                ('date_time', models.DateTimeField()),
                ('polarity', models.CharField(choices=[('0', 'Positive'), ('1', 'Neutral'), ('2', 'Negative')], max_length=10)),
                ('feed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
