# Generated by Django 2.0.3 on 2018-04-26 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HR', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='polarity',
            field=models.CharField(max_length=10),
        ),
    ]
