# Generated by Django 2.0.3 on 2018-04-26 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HR', '0003_employee_sex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='salary',
            field=models.CharField(max_length=30),
        ),
    ]
